replicaCount: 1

image:
  repository: ghcr.io/mlflow/mlflow
  tag: latest

service:
  type: ClusterIP
  port: 5000

backendStore:
  defaultSqlitePath: /tmp/mlflow.db

artifacts:
  defaultArtifactRoot: /tmp/mlruns

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi

persistence:
  enabled: false

postgresql:
  enabled: false

mysql:
  enabled: false

ingress:
  enabled: false