service:
  type: ClusterIP
  port: 80

auth:
  enabled: false

postgresql:
  enabled: false

mysql:
  enabled: false

backendStore:
  databaseConnectionCheck: false
  databaseMigration: false
  defaultSqlitePath: "/tmp/mlflow.db"

artifactRoot:
  defaultArtifactsDestination: "/tmp/mlartifacts"

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
