service:
  type: ClusterIP
  port: 5000

auth:
  enabled: false

# SQLite backend (ВАЖЛИВО для твого ДЗ)
backendStore:
  defaultSqlitePath: /tmp/mlflow.db

artifactRoot:
  defaultArtifactRoot: file:///mlruns

postgresql:
  enabled: false

mysql:
  enabled: false

minio:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 200m
    memory: 1Gi

persistence:
  enabled: false