apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-app
  namespace: infra-tools
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mlflow
    targetRevision: 1.4.0

    helm:
      valueFiles:
        - namespaces/application/mlflow-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true