helm:
  values:
   service:
   type: ClusterIP
   port: 5000

defaultArtifactRoot: file:///mlruns

auth:
  enabled: false

postgresql:
  enabled: false

mysql:
  enabled: false

minio:
  enabled: false

backendStore:
  databaseConnectionCheck: false

tracking:
  persistence:
    enabled: false

resources:
  requests:
    cpu: 100m
    memory: 512Mi