
service:
  type: ClusterIP
  port: 5000

auth:
  enabled: false

backendStore:
  defaultSqlitePath: /tmp/mlflow.db
  databaseConnectionCheck: false

postgresql:
  enabled: false

mysql:
  enabled: false

minio:
  enabled: false

tracking:
  persistence:
    enabled: false

resources:
  requests:
    cpu: 100m
    memory: 512Mi